"""Shared feature schema and API field mappings."""

MODEL_FEATURES = [
    "Lot Area",
    "Total Bsmt SF",
    "1st Flr SF",
    "2nd Flr SF",
    "Gr Liv Area",
    "Garage Area",
    "Overall Qual",
    "Overall Cond",
    "Year Built",
    "Year Remod/Add",
    "Bedroom AbvGr",
    "Full Bath",
    "Half Bath",
    "TotRms AbvGrd",
    "Fireplaces",
    "Garage Cars",
    "Neighborhood",
    "MS Zoning",
    "Bldg Type",
    "House Style",
    "Foundation",
    "Central Air",
    "Garage Type",
]

API_TO_MODEL_FIELDS = {
    "lot_area": "Lot Area",
    "total_bsmt_sf": "Total Bsmt SF",
    "first_flr_sf": "1st Flr SF",
    "second_flr_sf": "2nd Flr SF",
    "gr_liv_area": "Gr Liv Area",
    "garage_area": "Garage Area",
    "overall_qual": "Overall Qual",
    "overall_cond": "Overall Cond",
    "year_built": "Year Built",
    "year_remod_add": "Year Remod/Add",
    "bedroom_abvgr": "Bedroom AbvGr",
    "full_bath": "Full Bath",
    "half_bath": "Half Bath",
    "totrms_abvgrd": "TotRms AbvGrd",
    "fireplaces": "Fireplaces",
    "garage_cars": "Garage Cars",
    "neighborhood": "Neighborhood",
    "ms_zoning": "MS Zoning",
    "bldg_type": "Bldg Type",
    "house_style": "House Style",
    "foundation": "Foundation",
    "central_air": "Central Air",
    "garage_type": "Garage Type",
}
