version: "3.8"

services:
  fastapi:
    image: ml-fastapi:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: ml-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs
    environment:
      LOG_LEVEL: info
    restart: unless-stopped

  streamlit:
    image: ml-streamlit:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.streamlit
    container_name: ml-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ../logs:/app/logs
    environment:
      LOG_LEVEL: info
    restart: unless-stopped
